In [1]:
import numpy as np

In [2]:
#Creating 1D array
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [3]:
#(2,3) shape 2D array with zeros
arrz=np.zeros((2,3))
arrz

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#Using numpy.linspace to create an array of 5 evenly spaced numbers between 0 and 100
arr2=np.linspace(0,100,5)
arr2

array([  0.,  25.,  50.,  75., 100.])

In [5]:
#Creating 1D array
arr=np.array([5,10,15,20,25,30])

In [6]:
#Extracting 1st theree elemets
arr[:3]

array([ 5, 10, 15])

In [7]:
#Extracting every 2nd element
arr[::2]

array([ 5, 15, 25])

In [8]:
arr[3]=50
arr

array([ 5, 10, 15, 50, 25, 30])

In [9]:
#Creating a 1D array with 12 elements ranging from 1 to 12 using numpy.arange
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
#Reshaping to (3,4)
arr.shape=(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
#Creating 1D array
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [12]:
#Adding 10 to each element
arr+=10
arr

array([11, 12, 13, 14, 15])

In [13]:
#Multiplying by 3
arr*=3
arr

array([33, 36, 39, 42, 45])

In [14]:
#Square of eache element
arr**=2
arr

array([1089, 1296, 1521, 1764, 2025])

In [15]:
#Creating the 1D array
temp=np.array([30, 32, 31, 29, 28, 33, 34])
temp

array([30, 32, 31, 29, 28, 33, 34])

In [16]:
#Mean temperature
meanTemp=np.mean(temp)
meanTemp

np.float64(31.0)

In [17]:
#Minimum Temperature
minTemp=np.min(temp)
minTemp

np.int64(28)

In [18]:
#Maximum Temperature
maxTemp=np.max(temp)
maxTemp

np.int64(34)

In [19]:
total=np.sum(temp)
total

np.int64(217)

In [20]:
#sales of the products over 5 days
sales=np.array([[200, 220, 250, 270, 300],[150, 160, 170, 180, 200]])
sales

array([[200, 220, 250, 270, 300],
       [150, 160, 170, 180, 200]])

In [21]:
#Total Sales
totalSales=np.sum(sales,axis=1)
totalSales

array([1240,  860])

In [22]:
#Average sales
avgSales=np.mean(sales,axis=1)
avgSales

array([248., 172.])

In [23]:
#Highest sales for each product
maxSales=np.argmax(sales,axis=1)
maxSales

array([4, 4])